Repository sparcs-kaist/legacy-v3-otlplus-web, pull requests merged in 2024-03, with the labels that each got.

#36 Add Redux DevTools, Migrate to `arbitraryPlannerItem.tsx`
  src/App.jsx
  src/shapes/model/planner/arbitraryPlannerItem.tsx
  src/shapes/model/planner/futurePlannerItem.tsx
  src/shapes/model/planner/planner.tsx
  src/shapes/model/planner/takenPlannerItem.tsx
Labels: chore, migrate

#37 Migrate to `department.tsx`, `semester.tsx`, `course.tsx`
  src/shapes/model/subject/course.tsx
  src/shapes/model/subject/department.tsx
  src/shapes/model/subject/semester.tsx
Labels: migrate

#39 Migrate to `nestedCourse.tsx` `nestedLecture.tsx` `professor.tsx`
  src/shapes/model/subject/nestedCourse.tsx
  src/shapes/model/subject/nestedLecture.tsx
  src/shapes/model/subject/professor.tsx
Labels: migrate

#43 Migrate to `review.tsx`
  src/shapes/model/review/review.tsx
Labels: migrate

#41 Migrate to `user.tsx`
  src/shapes/model/session/user.tsx
Labels: migrate

#45 chore: disable pr preview on migration branch
  .github/workflows/pr-preview.yml
Labels: chore

#46 Add templates for Issue and PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/migration.md
Labels: chore

#48 Complement shapes migration
  src/shapes/enum.ts
  src/shapes/model/subject/Lecture.ts
  src/shapes/state/planner/ItemFocus.ts
Labels: migrate

#49 Prepare for migration
  index.html
  package.json
  src/hooks/useTranslatedString.tsx
  src/index.tsx
  tsconfig.json
  yarn.lock
Labels: migrate

#51 Migrate tile components
  src/components/sections/main/TodaysTimetableSection.jsx
  src/components/sections/planner/courselist/CourseListSection.jsx
  src/components/sections/planner/plannerandinfos/PlannerSubSection.jsx
  src/components/sections/timetable/timetableandinfos/TimetableSubSection.jsx
  src/components/tiles/HorizontalTimetableTile.jsx
  src/components/tiles/HorizontalTimetableTile.tsx
  src/components/tiles/PlannerTile.tsx
  src/components/tiles/TimetableDragTile.jsx
  src/components/tiles/TimetableDragTile.tsx
  src/components/tiles/TimetableTile.tsx
  src/sass/App.module.scss
  src/sass/App.module.scss.d.ts
  src/utils/itemUtils.js
  src/utils/itemUtils.ts
Labels: migrate

#50 Migrate course and project related blocks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/migration.md
  src/components/blocks/CourseBlock.jsx
  src/components/blocks/CourseBlock.tsx
  src/components/blocks/CourseSimpleBlock.jsx
  src/components/blocks/CourseSimpleBlock.tsx
  src/components/blocks/PlannerCourseBlock.jsx
  src/components/blocks/PlannerCourseBlock.tsx
  src/components/blocks/ProjectBlock.jsx
  src/components/blocks/ProjectBlock.tsx
Labels: migrate

#52 Fix review block and semester block
  src/components/blocks/ReviewBlock.tsx
  src/components/blocks/ReviewSimpleBlock.tsx
  src/components/blocks/ReviewWriteBlock.tsx
  src/components/blocks/SemesterBlock.jsx
  src/components/blocks/SemesterBlock.tsx
Labels: migrate

#53 Setup unit test with jest, testing-library
  .github/workflows/ci.yml
  README.md
  babel.config.js
  jest.config.js
  jest.setup.js
  package.json
  src/__mocks__/file.mock.js
  src/__mocks__/style.mock.js
  src/components/tiles/__tests__/HorizontalTimetableTile.test.tsx
  src/components/tiles/__tests__/PlannerTile.test.tsx
  src/components/tiles/__tests__/TimetableDragTile.test.tsx
  src/components/tiles/__tests__/TimetableTile.test.tsx
  src/test-utils.tsx
  yarn.lock
Labels: chore

#57 Fix#54, remove updateReview action in likedReviews reducer
  src/actions/write-reviews/likedReviews.js
  src/reducers/write-reviews/likedReviews.js
Labels: bug
